[package]
name = "poof"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
belly = { path = "../belly", version = "0.1.0" }
bevy = "0.9.1"
pecs = { path = "../bevy_promise" }
rand = "0.8.5"
